### ISSUE TITLE
BrowserSync + koyo =  resources + racket livereload <3

### ISSUE THREAD

**Issue by octplane** [Bogdanp/koyo#1]
Hello,

Starting from a sample koyo app, I quickly faced the fact that [broccoli-sass](https://github.com/joliss/broccoli-sass) is a bit old and thus can't work on my node.js installation (I'm at `v12.3.1`), so I decided to see if I could replace the broccoli pipeline by a more modern [gulp](https://gulpjs.com). 

This worked well. Then I realized that your nice Racket reloading code was pretty nice and efficient (although I got bit because translations changes do not trigger reloads) so I added Browsersync proxy-ing and live-reloading to the whole thing.

The result is testable at https://github.com/octplane/koyo-sample-browsersync and is a simple Koyo app with all this enabled:

- `gulp -T` will show the available tasks: not sure what should be kept and what should be thrown away
- I've updated the `Procfile.dev` to run the `gulp serve` task instead of the Broccoli code
- Browsersync also serves the static assets directly, it's probably faster than going through the Racket stack
- I've added a `plop` (poor naming) function in `dynamic.rkt` that is called through the `server` instanciation: this call browsersync and asks for a reload.

This way, the page gets automatically reloaded:

- whenever a change is done in resources (and gulp rebuilds the assets and reload the page)
- whenever the racket watcher decides to restart the server

The only annoying thing is that Browsersync opens the browser way too early and you have to reload the page once the Koyo app has started.

I believe this is a nice improvement to the standard koyo app and if you want, I'd happy to try and provide a PR to the blueprint so that this works out of the box for development. For production, the reloading hook should probably be removed. I confess I did not look at the way koyo packages the app for production.

Let me know what you think of that!

**Comment by Bogdanp** [comment]
I just tried your repo and I think it's very cool! I'd happily accept these changes to the standard blueprint, noting that, somewhere down the line, what I'd like to do is switch to a Racket-based asset pipeline (like `unlike-assets`, which was just posted to the mailing list this morning!) so we don't have to bring in any npm deps at all.

The one suggestion/change I'd make is I'd move the call to `plop` (and rename it to something like `sync-page`) inside of `start`, after the `(system-start prod-system)` call, guarded by a new configuration value (`browsersync` sould be fine). For production, a distribution is created starting with that `start` function, so all of the code is exactly as you run it locally. The only way to make things behave differently in different environments is to use config values (backed by environment variables).
