### ISSUE TITLE
User login is case-sensitive on emails

### ISSUE THREAD

**Issue by MarcKaufmann** [Bogdanp/koyo#14]
If I sign up with the email first_last@fastmail.com, then the login form chokes on FIRST_LAST@fastmail.com. It gives an `Invalid username or password.` error.

The signup form on the other hand realizes that FIRST_LAST@fastmail.com is already taken.

**Comment by Bogdanp** [comment]
This was fixed in c531ddc188267fa9befd665420623479ead8871d
