### ISSUE TITLE
Verification link sent on signup does not work when clicked, only when pasted

### ISSUE THREAD

**Issue by MarcKaufmann** [Bogdanp/koyo#15]
Today I had someone try to sign up on my webpage and clicking the link (in Chrome, on Windows) didn't work to get them to verify their email address. They had to open an incognito Window and paste in the link - although it may be that the incognito part was only necessary because the first click let to the page getting cached, and then copy-pasting not helping to get the actual webpage. 

This seems like the same issue as should have been addressed by commit 763da867b5de2c6b64062045c7572a2dbe51c26f. I checked and the code is updated accordingly in `dynamic.rkt`. Another user told me that they had gotten the same error, with a page showing forbidden popping up (that may have happened at another time, so it may not be related). 

The link HTML in the email (replacing website-url and secret key) is:

<a class=3D"button button--" style=3D"color: #FFF; background-color: #3869D4; border-top: 10px solid #3869D4; border-right: 18px solid #3869D4; border-bottom: 10px solid #3869D4; border-left:18px solid #3869D4; display: inline-block; text-decoration: none;border-radius: 3px; box-shadow: 0 2px 3px rgba(0,0,0,0.16); -webkit-text-size-adjust: none; box-sizing: border-box;" href=3D"https://<website-url>/verify/7/<SICRITKEYREMOVED>" target=3D"_blank">Verify your email</a>

I see nothing funky here, so I guess something is misconfigured on the server.

One possibility is that the live server isn't using the most recent code - but I'm using GitHub actions with your Racket action, so I don't think that's the case.

**Comment by Bogdanp** [comment]
I think this is now fixed in 6d77246812e926e8c0132785c5433008e464ced8, but we'll verify on Thursday.
