### ISSUE TITLE
[Question] Multi-context web application

### ISSUE THREAD

**Issue by AresAndy** [Bogdanp/koyo#30]
Hello,

Could you please provide a working example where under one app instance of ```koyo```, one is able to have lots of dispatch rules, separated per context? Maybe a stripped-down version of the e-commerce you've built with ```koyo```?

I am trying to see if I can use this framework to replace the Magento 2 nonsense, I've figured out few things already thanks to the power of Racket, and the nice things you provide with it but the (forward/backward) routing still remains obscure to me.

As of now the only way I see working is to litter the ```app.rkt``` file with let's say hundreds of dispatch rules under the same definition, with no clear distinction of context, other than the URL and the responder's name. 

Is there a nice way to do some sort of sub-routing without messing with the syntax rules of ```dispatch-rules+roles``` ?

 Plus some extra documentation on the ```koyo``` components over all would be nice. Some components are in dire need of some extra documentation and/or usage

Thanks in advance

**Comment by Bogdanp** [comment]
> Is there a nice way to do some sort of sub-routing without messing with the syntax rules of dispatch-rules+roles ?

Neither version of `dispatch-rules` compose the way you want them to, so you'd have to build your own macros on top to do this. Here's a rudimentary [example](https://gist.github.com/Bogdanp/8dbc89d303efd27e444bad21d466b21b).

> Plus some extra documentation on the koyo components over all would be nice. Some components are in dire need of some extra documentation and/or usage.

It would be helpful if you could list specific things you'd like to know how to do and we could improve things from there. Since I know how everything works, it's hard for me to determine which things need improvement without more specific requests.

**Comment by AresAndy** [comment]
>Neither version of dispatch-rules composes the way you want them to, so you'd have to build your own macros on top to do this.

Ok, this also applies if I want to move a few patterns in another file just to not let ```app.rkt``` become humongous, right?

> It would be helpful if you could list specific things you'd like to know how to do and we could improve things from there.

Hmm, of the top of my head:
- CORS: where those procedures should be called? In the config? In the app files?
- Dispatch: I could read that page a hundred times, and never fully understand what is going on. But the original macro from Racket is no better either actually :thinking: 
- Static: I guess it suffers from the same issue with dispatch, so all static content is forced to stay under the given folder (eg: no clear separation between JS/CSS from site images)

**Comment by Bogdanp** [comment]
> Ok, this also applies if I want to move a few patterns in another file just to not let app.rkt become humongous, right?

Yes, from that example, you could provide `site` and `resource` from one module

```racket
(provide (for-syntax site resource))
```

and require them in another and put them together with `dispatch-rules*`.

> CORS: where those procedures should be called? In the config? In the app files?

You'd add `wrap-cors` in your middleware stack in `app.rkt`, then use `current-csrf-token` in your handlers when building forms.

> Dispatch: I could read that page a hundred times, and never fully understand what is going on. But the original macro from Racket is no better either actually 🤔
> Static: I guess it suffers from the same issue with dispatch, so all static content is forced to stay under the given folder (eg: no clear separation between JS/CSS from site images)

Maybe this article will help: https://defn.io/2020/02/12/racket-web-server-guide/

You can have multiple static dispatchers that you chain together. I'll try to put together some more in-depth examples of all these things when I can find the time.
