### ISSUE TITLE
'raco koyo console' does not work.

### ISSUE THREAD

**Issue by chengzh2008** [Bogdanp/koyo#32]
when type 'raco koyo console', no module is loaded in to scope. 

![image](https://user-images.githubusercontent.com/6250306/128289954-926ddfd0-709d-4a3e-ba0e-6aac9bd729f4.png)

I was able to follow the video tutorial all of the content except this development repl through 'raco koyo console'. 

Not sure what I have missed. 

Thanks

**Comment by Bogdanp** [comment]
The console doesn't automatically load your modules, so you still have to require them yourself. I did make a recent breaking change to koyo console in that the `$%` syntax no longer works so you have to use `system-ref` (eg. `(system-ref 'db)`) to reference components from your system. You might also be interested in [this update](https://www.youtube.com/watch?v=wWj7OPvXGgA).
