### ISSUE TITLE
koyo/haml  multiple html attributes issue

### ISSUE THREAD

**Issue by AiziChen** [Bogdanp/koyo#33]
For example:
```racket
(haml
  (.c1.c2
    ([:class "c3"]
     [:class "c4"])))
```

there will produce:

```racket
'(div ((class "c1 c2") (class "c3") (class "c4")))
```

but browser don't support these format. browser automatically remove others same attributes, not only `class` attributes.

**Comment by Bogdanp** [comment]
What would you expect to happen here? Should HAML raise an error? Or should it try to merge all the classes together?

**Comment by AiziChen** [comment]
@Bogdanp
merge all the classes together. 
I want this:
```
'(div ((class "c1 c2 c3 c4")))
```
because sometimes need to dynamically pass in parameters for class attribute.
