### ISSUE TITLE
Break koyo/mime module into own package?

### ISSUE THREAD

**Issue by winny-** [Bogdanp/koyo#44]
Hey Bogdan, I've been playing a bit with web servers in racket.  Much to my surprise, there wasn't an utility procedure to lookup mime types shipped with web-server-lib (to the best of my knowledge).  Did some research and found koyo ships with a mime lookup module (`koyo/mime`).  I have a feeling many users using web-server may want to utilize this module in particular.

Would it make sense to break it out into its own package?  This would eliminate some present gotchas, such as https://github.com/97jaz/gregor/pull/51 through stripping out most dependencies that koyo depends on.

What do you think?

Thanks,
Winny

**Comment by Bogdanp** [comment]
Hi Winny, I've gone ahead and extracted this functionality into https://github.com/Bogdanp/racket-net-mime-type .

**Comment by winny-** [comment]
Thank you!  I'll be using this right away :)
