### ISSUE TITLE
locale file not reloading

### ISSUE THREAD

**Issue by tbmreza** [Bogdanp/koyo#47]
I'm just trying out the example app generated with `raco koyo new`. It seems that triggering reloading by modifying the translation file (e.g. in the example app `resources/locales/en/us.rktd`)  isn't enough, I need to stop the server and restart.
 
Are rktd files not a subject to reloading that's discussed [here](https://github.com/Bogdanp/koyo/issues/19#issuecomment-889663954)?

**Comment by Bogdanp** [comment]
Thanks for the report! This was a regression introduced when I improved the way code is reloaded.

To fix it in your app, you'll have to make the same changes as in https://github.com/Bogdanp/koyo/commit/5e70f5c38eb1731921b490734a9178f97f01998c to your project.

**Comment by tbmreza** [comment]
Awesome, thanks ^^ @Bogdanp
