### ISSUE TITLE
Making tracked file extensions / paths configurable

### ISSUE THREAD

**Issue by jaybonthius** [Bogdanp/koyo#57]
Would it be possible to allow the user to configure the tracked file paths / extensions?

I'm using Koyo to serve files generated by a Pollen preprocessor. During development, I have Koyo make requests to the Pollen project server. This works pretty well for the most part—when I make a change to a source file, the file is re-rendered by Pollen when requested via Koyo, as desired. However, the update to the HTML file triggers a Koyo application reload, causing the initial request to fail. A second request is then required to successfully retrieve the page. This cycle repeats on every request, necessitating a first click to trigger the Pollen re-render, followed by a second click to actually receive the content from the server.

I experimented with removing the `.html` extension from the list of tracked file extensions in `track-file?`, and this gave me the desired behavior. Now everything runs smoothly: I make a change to a Pollen source file, and the request returns instantly from Koyo, without triggering an application reload.

https://github.com/Bogdanp/koyo/blob/acdee87e97c712ac56d827100311caa7c32074ec/koyo-lib/koyo/runner.rkt#L25-L36

If I had the option of configuring tracked file paths / extensions in the Koyo project setup, that would be really awesome. 

On a related note, I have other `.rkt` files in my directory (Pollen things) that do not directly relate to the Koyo project. Any changes to _those_ files also trigger a reload. So it might be nice if the tracked files could be configured by filename globs (e.g. track `project/**/*.rkt`).

P.S. thank you for all your work on these packages!

**Comment by Bogdanp** [comment]
Since this code is part of the runner, I think probably the way to go here is to add a command line flag (or flags) to overwrite the behavior of `track-file?`, probably something along the lines of a repeatable `--watch-pattern <glob>` flag and maybe a separate `--watch-exclude <glob>` flag. I'll play around with this next weekend.

**Comment by Bogdanp** [comment]
@jaybonthius would you mind giving https://github.com/Bogdanp/koyo/pull/58 a try and let me know what you think?

Instead of globs, the patterns are regular expressions, and you can pass the `--log-watched-files` flag to see which paths get tracked.

**Comment by Bogdanp** [comment]
I would try:

```
raco koyo serve --watch-pattern 'project(/.*\\.rkt)?$' --log-watched-files
```

directories that don't match any of the patterns are skipped, so at least one pattern must match the project dir.
